version: '3'
services:
  client:
    build: ./client
    environment:
     - REACT_APP_SERVER_URL=http://server:3001
    ports:
      - "3000:3000"

  server:
    build: ./server
    env_file:
      - production.env
    ports:
      - "3001:3001"
    volumes:
      - ".env:/app/.env"


  #add a service for database
  db:
    image: postgres:latest
    depends_on:
      server:
        condition: service_started
        required: true
    env_file:
      - production.env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"