version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"

  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ".env:/app/.env"


  #add a service for database
  db:
    image: postgres:latest
    depends_on:
      server:
        condition: service_started
        required: true
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./server/sqlseeds/startup.sql:/docker-entrypoint-initdb.d/startup.sql

# Add a volume for persisting database data
volumes:
  stonks: